name: Debug Build Pipeline

on:
  push:
    branches: [ debug ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Frontend
        run: npm install
      - name: Build Tauri
        run: npm run tauri build > build_output.log 2>&1
        continue-on-error: true
      - name: Commit Log
        run: |
          git config --global user.name "Log Bot"
          git config --global user.email "bot@example.com"
          git add build_output.log
          git commit -m "Add build log"
          git push
